PROMPT = "prompt"
MODEL = "model"
STREAM = "stream"
TIME_OUT_OLLAMA_MSSG = "Error: Timed out waiting for Ollama to respond."
INTERNAL_SERVER_ERROR = "Internal server error occurred, Please contact the admin."
OLLAMA_TIME_OUT = 300 # value in ms
OLLAMA_STREAM = False
CHAT_ROUTE_URL = "/chat"
CHAT_HISTORY_FILE = "chat_history.json"
CLEAR_CHAT_ROUTE_URL = "/clear-chat"
GET_CHAT_HISTORY_ROUTE_URL = "/chat-history"